/**
 * Publisher for the LOK Card Universe. Projects this game's cards and
 * LokToken-priced cosmetics into SQL the shared LokServices project can
 * apply (see Lok-EcoSystsem/LokToken EcoSystem/LOK_CARD_UNIVERSE.md).
 *
 *   pnpm exec tsx scripts/export-lok-registry.ts <outDir>
 *
 * Writes `survivor616.cards.sql` (upserts into lok_cards) and
 * `survivor616.catalog.sql` (upserts into lok_catalog). Both are idempotent,
 * so re-running after content changes is the whole "sync" step.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { CARD_MANIFESTS, CARD_PACKS } from '../src/game/data/cards';
import { artRecipeFor } from '../src/game/data/cardArt';
import { THEMED_PALETTES } from '../src/game/data/themedPalettes';
import { RUN_AURAS } from '../src/game/data/runAuras';
import { HATS } from '../src/game/data/hats';
import { CELEBRATIONS } from '../src/game/data/celebrations';
import { combatForRarity } from '../../../lib/lok-client/src/cards';
import { LOKTOKEN_PRICE_BY_TIER, catalogSku } from '../src/lib/lokStoreCatalog';

const APP_KEY = 'survivor616';
const NS = 'g6.616-survivor';
const q = (value: string | null | undefined) => (value == null ? 'null' : `'${value.replace(/'/g, "''")}'`);
const j = (value: unknown) => `${q(JSON.stringify(value))}::jsonb`;

const packFor = (setId: string) => CARD_PACKS.find((pack) => pack.id === setId);

const cardRows = CARD_MANIFESTS.map((card) => {
  const meta = (card.metadata ?? {}) as { setId?: string; cardNumber?: string; subjectType?: string };
  const setId = meta.setId ?? 'misc';
  const kindOfSubject = meta.subjectType === 'enemy' ? 'enemy' : meta.subjectType === 'lokpet' ? 'companion' : 'hero';
  return `(${q(card.id)},${q(APP_KEY)},${q(NS)},${q(setId)},${q(packFor(setId)?.name)},${q(meta.cardNumber)},${q(card.kind)},${q(card.name)},${q(card.description)},${q(card.rarity)},array[${(card.tags ?? []).map(q).join(',')}]::text[],${j(combatForRarity(card.rarity, kindOfSubject))},${j(artRecipeFor(card))},${j(card)})`;
});

const cardsSql = `-- Generated by artifacts/survivor-616/scripts/export-lok-registry.ts -- do not hand-edit.
insert into public.lok_cards (asset_id,source_game,namespace,set_id,set_name,card_number,kind,name,description,rarity,tags,combat,art,manifest)
values
${cardRows.join(',\n')}
on conflict (asset_id) do update set
  set_id=excluded.set_id, set_name=excluded.set_name, card_number=excluded.card_number, name=excluded.name,
  description=excluded.description, rarity=excluded.rarity, tags=excluded.tags, combat=excluded.combat, art=excluded.art,
  manifest=excluded.manifest, updated_at=now();
`;

type Priced = { id: string; name: string; description: string; tier?: string; cost: number };
const section = (kind: 'palette' | 'aura' | 'hat' | 'celebration', itemType: string, items: Priced[]) =>
  items
    .filter((item) => item.cost > 0)
    .map((item) => {
      const tier = item.tier ?? 'standard';
      const price = LOKTOKEN_PRICE_BY_TIER[tier] ?? LOKTOKEN_PRICE_BY_TIER.standard!;
      return `((select id from public.lok_tenants limit 1),${q(catalogSku(kind, item.id))},array[${q(APP_KEY)}],'${itemType}'::lok_item_type,${q(item.name)},${q(item.description)},${price},${q(tier === 'standard' ? 'common' : tier)},${j({ kind, id: item.id })},true)`;
    });

const catalogRows = [
  ...section('palette', 'theme', THEMED_PALETTES),
  ...section('aura', 'cosmetic', RUN_AURAS),
  ...section('hat', 'cosmetic', HATS),
  ...section('celebration', 'cosmetic', CELEBRATIONS),
];

const catalogSql = `-- Generated by artifacts/survivor-616/scripts/export-lok-registry.ts -- do not hand-edit.
-- PLACEHOLDER PRICES (see LOKTOKEN_PRICE_BY_TIER): adjust by editing the table and re-running.
insert into public.lok_catalog (tenant_id,sku,app_scope,item_type,name,description,price,rarity,payload,active)
values
${catalogRows.join(',\n')}
on conflict (tenant_id, sku) do update set
  name=excluded.name, description=excluded.description, price=excluded.price, rarity=excluded.rarity, payload=excluded.payload;
`;

const outDir = process.argv[2] ?? '.';
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'survivor616.cards.sql'), cardsSql);
writeFileSync(join(outDir, 'survivor616.catalog.sql'), catalogSql);
console.log(`${cardRows.length} cards, ${catalogRows.length} catalog items -> ${outDir}`);
